export const ProfileDummy = [
  {
    id: 1,
    title: 'Order history',
    desc: 'View all your orders, past and present',
    icon: 'briefcase-outline',
    navigation: 'MY_ORDERS',
  },
  {
    id: 2,
    title: 'Vouchers',
    desc: 'Easily add, view or redeem',
    icon: 'card-outline',
    navigation: 'MY_VOUCHERS',
  },
  {
    id: 3,
    title: 'My account',
    desc: 'Manage your personal details and settings',
    icon: 'person-outline',
    navigation: 'MY_ACCOUNT',
  },
  {
    id: 4,
    title: 'Address book',
    desc: 'Add or edit your shipping addresses',
    icon: 'business-outline',
    navigation: 'MY_ADDRESS',
  },
  {
    id: 5,
    title: 'Tickets & events',
    desc: 'Explore your points, level and rewarded',
    icon: 'gift-outline',
    navigation: 'MY_TICKET',
  },
  {
    id: 6,
    title: 'Made to be remade',
    desc: 'Send us your old cake and get rewarded',
    icon: 'repeat-outline',
    navigation: 'MY_REMADE',
  },
  {
    id: 7,
    title: 'Need help',
    desc: 'Find FAQs or connect with our support team',
    icon: 'help-outline',
    navigation: 'SUPPORT',
  },
  {
    id: 8,
    title: 'Invite a friend',
    desc: 'Share the love and get a $10 discount voucher',
    icon: 'people-outline',
    navigation: 'INVITE_FRIEND',
  },
];
