export const dummyData1 = [
  {
    id: 1,
    title: 'Cream Butter Scone',
    categories: ['Bread & Pastry'],
    price: '200',
    img: 'https://www.tljus.com/wp-content/uploads/2022/07/Web_PDP_ChocoCloudCake.png',
  },
  {
    id: 2,
    title: 'Taro Cream Bread',
    type: ['Bread & Pastry'],
    price: '300',
    img: 'https://www.tljus.com/wp-content/uploads/2022/06/Web_PDP_OrangeCreamCake.png',
  },
  {
    id: 3,
    title: 'Sweet Brown Roll',
    type: ['Bread & Pastry'],
    price: '100',
    img: 'https://www.tljus.com/wp-content/uploads/2022/06/Web_PDP_MochaCloud_1.png',
  },
  {
    id: 4,
    title: 'Taro Buttercream Bread',
    type: ['Bread & Pastry'],
    price: '400',
    img: 'https://www.tljus.com/wp-content/uploads/2020/07/PeachCake.jpg',
  },
  {
    id: 5,
    title: 'Strawberry Cream Soboro',
    type: ['Bread & Pastry'],
    price: '10',
    img: 'https://www.tljus.com/wp-content/uploads/2019/12/bread-11.jpg',
  },
  {
    id: 6,
    title: 'Toast Pan Bread',
    type: ['Bread & Pastry'],
    price: '200',
    img: 'https://www.tljus.com/wp-content/uploads/2019/12/bread-03.jpg',
  },
  {
    id: 7,
    title: 'Sweet Frank Roll',
    type: ['Bread & Pastry'],
    price: '50',
    img: 'https://www.tljus.com/wp-content/uploads/2019/12/bread-09.jpg',
  },
  {
    id: 8,
    title: 'Croque Monsieur',
    type: ['Bread & Pastry'],
    price: '200',
    img: 'https://www.tljus.com/wp-content/uploads/2019/12/bread-10.jpg',
  },
];
